### ISSUE TITLE
Unable to create a profile on Tamo 5.0.1

### ISSUE THREAD

**Issue by LegitCps** [anthonynarlock/TamoStudy#29]
Hi! I just installed Tamo 5, and I can't create a local profile. I enter my settings, and when I press "Create", nothing happens. To save time and help resolve the problem, here are the logs that I was able to display using the "java -jar TamoStudy_Beta_v5.0.1.jar" command in cmd.
Edited : I use Windows 11 with the latest version of Java 8 (build 1.8.0_391-b13)
I don't have "profiles.json" on my TamoStudy folder

java -jar TamoStudy_Beta_v5.0.1.jar
2023-10-24 19:10:32 [INFO] : TamoStudy.main : TamoStudy program starting to run.
2023-10-24 19:10:33 [INFO] : GlobalSettingsJsonManager.readJson : Attempting to read globalSettings.json
2023-10-24 19:10:33 [INFO] : WelcomeGUI.initializeAttributes : Loaded Global Settings: GlobalSettings [language=ENG, defaultLocalProfile=-1, receiveUpdateNotifications=true]
2023-10-24 19:10:35 [INFO] : ProfileJsonManager.readJson : Attempting to read profiles.json
2023-10-24 19:10:35 [INFO] : ProfileJsonManager.readJson : No profiles were found
2023-10-24 19:10:45 [INFO] : ProfileJsonManager.readJson : Attempting to read profiles.json
2023-10-24 19:10:45 [INFO] : ProfileJsonManager.readJson : No profiles were found
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;)Ljava/util/List;
        at model.profile.Profile.<init>(Profile.java:66)
        at components.panel.ProfileSelectionPanel$5.actionPerformed(ProfileSelectionPanel.java:458)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.WaitDispatchSupport$2.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.awt.WaitDispatchSupport$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(Unknown Source)
        at java.awt.Dialog.show(Unknown Source)
        at javax.swing.JOptionPane.showOptionDialog(Unknown Source)
        at gui.WelcomeGUI$3.actionPerformed(WelcomeGUI.java:177)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
        
Please help me :(

**Comment by LegitCps** [comment]
I have find a solution : use JDK-21

**Comment by narlock** [comment]
I had a suspicion this was the reason. It is interesting. Using Java 8 (1.8.0_381) on my Windows 11 machine works. But it seems that some Java 8 versions when running on a Windows device seem to have problems specifically with the `List.of` function... I will be updating this to make the logic use a different method.

Thank you for tracking this down, I was not experiencing this with any of my devices. I will put in this fix and then tag you, if you are able to run with your old Java version and test. Let me know, if not, all good.

**Comment by narlock** [comment]
I would guess any Java version past Java 8 would work, but I would prefer the use of 11, 17 instead of Java 21

**Comment by narlock** [comment]
The JAR file for the latest pre-release has been updated. The issue was most likely because I was originally compiling to 1.8 using openjdk 17. I recompiled the code using 1.8 and it appears to have resolved the issue.

thanks to @GautMenon for helping test the resolution
